name: Test branch

on:
  push:
    branches-ignore:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        registry-url: 'https://registry.npmjs.org'

    - run: npm ci --ignore-scripts
    - run: npm run bootstrap --ignore-scripts
    - run: npm run lint
    - run: npm run compile
    - run: npm run ci-test
    - run: npm run ci-version

    - uses: IgnusG/jest-report-action@v2.3.3
      if: always()
      with:
        access-token: ${{ secrets.GITHUB_TOKEN }}