name: Publish to npm

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        registry-url: 'https://registry.npmjs.org'
        token: ${{ secrets.NPM_TOKEN }}

    - run: git config --local user.name "ci-bot"
    - run: git config --local user.email "npm@clave.no"
    - run: npm whoami

    - run: npm ci --ignore-scripts
    - run: npm run bootstrap
    - run: npm run ci-publish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
