name: Check Pull-request

on: pull_request_target

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ env.LERNA_VERSIONS }}
    steps:

    # Checkout all commits, so we get previous tags
    # The ref and repository is needed since we use on: pull_request_target
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.ref }}
        repository: ${{ github.event.pull_request.head.repo.full_name }}
        fetch-depth: 0

    # This is needed because pull-requests don't run on branches
    # so we create a new branch to work on
    - run: git switch -c "pull-request"

    # This is needed so that ci-version can create git tags
    - name: Set git user
      run: |
        git config --local user.name "ci-bot"
        git config --local user.email "npm@clave.no"

    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        registry-url: 'https://registry.npmjs.org'

    # Install npm packages
    - run: npm ci

    # This is what we really want to do in this whole yml file
    - run: npm run ci-pullrequest

    # Look at the tags that have been generated
    - name: Get new versions
      id: versions
      run: |
        echo 'LERNA_VERSIONS<<EOF' >> $GITHUB_ENV
        git tag --points-at HEAD >> $GITHUB_ENV
        echo 'EOF' >> $GITHUB_ENV

  comment:
    runs-on: ubuntu-latest
    needs: check
    steps:
    # Create a comment in the pull request using the tags created
    - uses: marocchino/sticky-pull-request-comment@v1
      if: needs.check.outputs.version != ''
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        message: |
          The following versions will be created when this pull-request is merged:
          ```
          ${{ needs.check.outputs.version }}
          ```
    - uses: marocchino/sticky-pull-request-comment@v1
      if: needs.check.outputs.version == ''
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        message: |
          No packages will be created when this pull-request is merged