name: Check Pull-request

on:
  - pull_request_target
  - pull_request

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        registry-url: 'https://registry.npmjs.org'

    - run: npm ci --ignore-scripts
    - run: npm run bootstrap --ignore-scripts
    - run: npm run ci-lint
    - run: npm run ci-test
    - run: npm run compile
    - run: npm run ci-version
    - name: Get new versions
      id: versions
      run: |
        echo 'releases<<EOF' >> $GITHUB_ENV
        git tag --points-at HEAD >> $GITHUB_ENV
        echo 'EOF' >> $GITHUB_ENV
    - uses: marocchino/sticky-pull-request-comment@v1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        message: |
          The following versions will be created when this pull-request is merged:
          ```
          ${{ steps.versons.outputs.releases }}
          ```