name: Check Pull-request

on: pull_request_target

jobs:
  check:
    runs-on: ubuntu-latest
    steps:

    # Checkout all commits, so we get previous tags
    # The ref and repository is needed since we use on: pull_request_target
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.ref }}
        repository: ${{ github.event.pull_request.head.repo.full_name }}
        fetch-depth: 0

    # The following line checks if this repository is vulnerable for using pull_request_target
    # It will not show up in the build log until the pr is merged. Therefore it is not a problem
    # to use pull_request_target with secrets in the build script.
    - run: echo "This will not show up in the log until this is merged to master"

    # This is needed because pull-requests don't run on branches
    # so we create a new branch to work on
    - run: git switch -c "pull-request"

    # This is needed so that ci-version can create git tags
    - name: Set git user
      run: |
        git config --local user.name "ci-bot"
        git config --local user.email "npm@clave.no"

    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        registry-url: 'https://registry.npmjs.org'

    # Install npm packages
    - run: npm ci

    # This is what we really want to do in this whole yml file
    - run: npm run ci-pullrequest

    # Look at the tags that have been generated
    - name: Get new versions
      id: versions
      run: |
        echo 'LERNA_VERSIONS<<EOF' >> $GITHUB_ENV
        git tag --points-at HEAD >> $GITHUB_ENV
        echo 'EOF' >> $GITHUB_ENV

    # Create a comment in the pull request using the tags created
    - uses: marocchino/sticky-pull-request-comment@v1
      if: env.LERNA_VERSIONS != ''
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        message: |
          The following versions will be created when this pull-request is merged:
          ```
          ${{ env.LERNA_VERSIONS }}
          ```
    - uses: marocchino/sticky-pull-request-comment@v1
      if: env.LERNA_VERSIONS == ''
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        message: |
          No packages will be created when this pull-request is merged